#!/bin/bash
rm -r results.txt
rm -r results_inst.txt
echo "--------------------------------------------"
bash ./compare.sh opdhphse OPT_dhphase OPT_clingcon "900" 
echo "--------------------------------------------"
bash ./compare.sh opdhctrphs OPT_dhctrphs OPT_clingcon "900"
echo "--------------------------------------------"
bash ./compare.sh opdhextphs OPT_dhextphs OPT_clingcon "900" 
echo "--------------------------------------------"
#bash ./compare.sh opdhctrphs OPT_dhctrphs OPT_dhphase "900"
#echo "--------------------------------------------"
#bash ./compare.sh opdhextphs OPT_dhextphs OPT_dhphase "900" "ok"
#echo "--------------------------------------------"
#bash ./compare.sh ophphase OPT_hphase OPT_clingcon "900" 
#echo "--------------------------------------------"
#bash ./compare.sh ophplink OPT_hplink OPT_clingcon "900"
echo "--------------------------------------------"
bash ./compare.sh "hphase(-theory)" OPT_hphase OPT_clingcon "900" 
echo "--------------------------------------------"
bash ./compare.sh "hlink(-theory)" OPT_hplink OPT_clingcon "900"
echo "--------------------------------------------"
bash ./compare.sh opdhplink OPT_dhplink OPT_clingcon "900" 
echo "--------------------------------------------"
bash ./compare.sh opdhchange OPT_dhchange OPT_clingcon "900" 
echo "--------------------------------------------"
bash ./compare.sh opdhxplink OPT_dhxplink OPT_clingcon "900" 
echo "--------------------------------------------"
bash ./compare.sh opdhxphase OPT_dhxphase OPT_clingcon "900" 
echo "--------------------------------------------"
#bash ./compare.sh opclinotime OPT_clinotime OPT_clingcon "900" 
#echo "--------------------------------------------"
bash ./compare.sh hlink OPT_dhxplink OPT_clingcon "900" 
echo "--------------------------------------------"
bash ./compare.sh hphase OPT_dhxphase OPT_clingcon "900"  
echo "--------------------------------------------"
#bash ./compare.sh clingcon OPT_clingcon OPT_clingcon "900" "ok" 
#echo "--------------------------------------------"
bash ./compare.sh dhphase+ OPT_dhxphase_plus OPT_clingcon "900" "ok"
echo "--------------------------------------------"
